{% set name = "requests" %}
{% set version = "2.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/requests-{{ version }}.tar.gz
  sha256: d568723a7ebd25875d8d1eaf5dfa068cd2fc8194b2e483d7b1f7c81918dbec6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi >=2017.4.17
    - charset-normalizer >=2.0.0,<2.1
    - idna >=2.5,<4
    - urllib3 >=1.21.1,<1.27
  # https://github.com/psf/requests/blob/da9996fe4dc63356e9467d0a5e10df3d89a8528e/requests/__init__.py#L103-L115
  run_constrained:
    - chardet >=3.0.2,<5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Requests is an elegant and simple HTTP library for Python, built with ♥.
  dev_url: https://github.com/psf/requests

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
    - carlodri
